/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Filekyso service. Represents a row in the &quot;Timekeeping_Filekyso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.backend.model.impl.FilekysoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.backend.model.impl.FilekysoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Filekyso
 * @generated
 */
@ProviderType
public interface FilekysoModel extends BaseModel<Filekyso> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a filekyso model instance should use the {@link Filekyso} interface instead.
	 */

	/**
	 * Returns the primary key of this filekyso.
	 *
	 * @return the primary key of this filekyso
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this filekyso.
	 *
	 * @param primaryKey the primary key of this filekyso
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this filekyso.
	 *
	 * @return the ID of this filekyso
	 */
	public int getId();

	/**
	 * Sets the ID of this filekyso.
	 *
	 * @param id the ID of this filekyso
	 */
	public void setId(int id);

	/**
	 * Returns the file_id_nosigned of this filekyso.
	 *
	 * @return the file_id_nosigned of this filekyso
	 */
	public long getFile_id_nosigned();

	/**
	 * Sets the file_id_nosigned of this filekyso.
	 *
	 * @param file_id_nosigned the file_id_nosigned of this filekyso
	 */
	public void setFile_id_nosigned(long file_id_nosigned);

	/**
	 * Returns the trangthai of this filekyso.
	 *
	 * @return the trangthai of this filekyso
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this filekyso.
	 *
	 * @param trangthai the trangthai of this filekyso
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the fileurl_signed of this filekyso.
	 *
	 * @return the fileurl_signed of this filekyso
	 */
	@AutoEscape
	public String getFileurl_signed();

	/**
	 * Sets the fileurl_signed of this filekyso.
	 *
	 * @param fileurl_signed the fileurl_signed of this filekyso
	 */
	public void setFileurl_signed(String fileurl_signed);

	/**
	 * Returns the nguoilamdon_id of this filekyso.
	 *
	 * @return the nguoilamdon_id of this filekyso
	 */
	public long getNguoilamdon_id();

	/**
	 * Sets the nguoilamdon_id of this filekyso.
	 *
	 * @param nguoilamdon_id the nguoilamdon_id of this filekyso
	 */
	public void setNguoilamdon_id(long nguoilamdon_id);

	/**
	 * Returns the nguoikydon_id of this filekyso.
	 *
	 * @return the nguoikydon_id of this filekyso
	 */
	public long getNguoikydon_id();

	/**
	 * Sets the nguoikydon_id of this filekyso.
	 *
	 * @param nguoikydon_id the nguoikydon_id of this filekyso
	 */
	public void setNguoikydon_id(long nguoikydon_id);

	/**
	 * Returns the created_at of this filekyso.
	 *
	 * @return the created_at of this filekyso
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this filekyso.
	 *
	 * @param created_at the created_at of this filekyso
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this filekyso.
	 *
	 * @return the updated_at of this filekyso
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this filekyso.
	 *
	 * @param updated_at the updated_at of this filekyso
	 */
	public void setUpdated_at(Date updated_at);

	@Override
	public Filekyso cloneWithOriginalValues();

}