/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the tudanhgia service. Represents a row in the &quot;Timekeeping_tudanhgia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.backend.model.impl.tudanhgiaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.backend.model.impl.tudanhgiaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tudanhgia
 * @generated
 */
@ProviderType
public interface tudanhgiaModel extends BaseModel<tudanhgia> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tudanhgia model instance should use the {@link tudanhgia} interface instead.
	 */

	/**
	 * Returns the primary key of this tudanhgia.
	 *
	 * @return the primary key of this tudanhgia
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this tudanhgia.
	 *
	 * @param primaryKey the primary key of this tudanhgia
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this tudanhgia.
	 *
	 * @return the ID of this tudanhgia
	 */
	public int getId();

	/**
	 * Sets the ID of this tudanhgia.
	 *
	 * @param id the ID of this tudanhgia
	 */
	public void setId(int id);

	/**
	 * Returns the user_id of this tudanhgia.
	 *
	 * @return the user_id of this tudanhgia
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this tudanhgia.
	 *
	 * @param user_id the user_id of this tudanhgia
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the thongtintudanhgia of this tudanhgia.
	 *
	 * @return the thongtintudanhgia of this tudanhgia
	 */
	@AutoEscape
	public String getThongtintudanhgia();

	/**
	 * Sets the thongtintudanhgia of this tudanhgia.
	 *
	 * @param thongtintudanhgia the thongtintudanhgia of this tudanhgia
	 */
	public void setThongtintudanhgia(String thongtintudanhgia);

	/**
	 * Returns the ykienkhac of this tudanhgia.
	 *
	 * @return the ykienkhac of this tudanhgia
	 */
	@AutoEscape
	public String getYkienkhac();

	/**
	 * Sets the ykienkhac of this tudanhgia.
	 *
	 * @param ykienkhac the ykienkhac of this tudanhgia
	 */
	public void setYkienkhac(String ykienkhac);

	/**
	 * Returns the file_url of this tudanhgia.
	 *
	 * @return the file_url of this tudanhgia
	 */
	@AutoEscape
	public String getFile_url();

	/**
	 * Sets the file_url of this tudanhgia.
	 *
	 * @param file_url the file_url of this tudanhgia
	 */
	public void setFile_url(String file_url);

	/**
	 * Returns the tongdiem of this tudanhgia.
	 *
	 * @return the tongdiem of this tudanhgia
	 */
	public double getTongdiem();

	/**
	 * Sets the tongdiem of this tudanhgia.
	 *
	 * @param tongdiem the tongdiem of this tudanhgia
	 */
	public void setTongdiem(double tongdiem);

	/**
	 * Returns the trangthaixacnhan of this tudanhgia.
	 *
	 * @return the trangthaixacnhan of this tudanhgia
	 */
	public int getTrangthaixacnhan();

	/**
	 * Sets the trangthaixacnhan of this tudanhgia.
	 *
	 * @param trangthaixacnhan the trangthaixacnhan of this tudanhgia
	 */
	public void setTrangthaixacnhan(int trangthaixacnhan);

	/**
	 * Returns the trangthaikyso of this tudanhgia.
	 *
	 * @return the trangthaikyso of this tudanhgia
	 */
	public int getTrangthaikyso();

	/**
	 * Sets the trangthaikyso of this tudanhgia.
	 *
	 * @param trangthaikyso the trangthaikyso of this tudanhgia
	 */
	public void setTrangthaikyso(int trangthaikyso);

	/**
	 * Returns the thang of this tudanhgia.
	 *
	 * @return the thang of this tudanhgia
	 */
	public int getThang();

	/**
	 * Sets the thang of this tudanhgia.
	 *
	 * @param thang the thang of this tudanhgia
	 */
	public void setThang(int thang);

	/**
	 * Returns the nam of this tudanhgia.
	 *
	 * @return the nam of this tudanhgia
	 */
	public int getNam();

	/**
	 * Sets the nam of this tudanhgia.
	 *
	 * @param nam the nam of this tudanhgia
	 */
	public void setNam(int nam);

	/**
	 * Returns the phongban_id of this tudanhgia.
	 *
	 * @return the phongban_id of this tudanhgia
	 */
	public long getPhongban_id();

	/**
	 * Sets the phongban_id of this tudanhgia.
	 *
	 * @param phongban_id the phongban_id of this tudanhgia
	 */
	public void setPhongban_id(long phongban_id);

	/**
	 * Returns the xeploai of this tudanhgia.
	 *
	 * @return the xeploai of this tudanhgia
	 */
	@AutoEscape
	public String getXeploai();

	/**
	 * Sets the xeploai of this tudanhgia.
	 *
	 * @param xeploai the xeploai of this tudanhgia
	 */
	public void setXeploai(String xeploai);

	/**
	 * Returns the created_at of this tudanhgia.
	 *
	 * @return the created_at of this tudanhgia
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this tudanhgia.
	 *
	 * @param created_at the created_at of this tudanhgia
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this tudanhgia.
	 *
	 * @return the updated_at of this tudanhgia
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this tudanhgia.
	 *
	 * @param updated_at the updated_at of this tudanhgia
	 */
	public void setUpdated_at(Date updated_at);

	@Override
	public tudanhgia cloneWithOriginalValues();

}