/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.backend.model.impl;

import com.liferay.docs.backend.model.adminphieudiem;
import com.liferay.docs.backend.model.adminphieudiemModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the adminphieudiem service. Represents a row in the &quot;Timekeeping_adminphieudiem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>adminphieudiemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link adminphieudiemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see adminphieudiemImpl
 * @generated
 */
@JSON(strict = true)
public class adminphieudiemModelImpl
	extends BaseModelImpl<adminphieudiem> implements adminphieudiemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a adminphieudiem model instance should use the <code>adminphieudiem</code> interface instead.
	 */
	public static final String TABLE_NAME = "Timekeeping_adminphieudiem";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.INTEGER}, {"uuid_", Types.VARCHAR},
		{"user_id", Types.BIGINT}, {"nhomcauhoi", Types.VARCHAR},
		{"noidungcauhoi", Types.VARCHAR}, {"thuocnhomcauhoinao", Types.INTEGER},
		{"diemtoida", Types.DOUBLE}, {"trangthaicauhoi", Types.BIGINT},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("user_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nhomcauhoi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noidungcauhoi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("thuocnhomcauhoinao", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("diemtoida", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("trangthaicauhoi", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Timekeeping_adminphieudiem (id_ INTEGER not null primary key,uuid_ VARCHAR(75) null,user_id LONG,nhomcauhoi VARCHAR(75) null,noidungcauhoi VARCHAR(75) null,thuocnhomcauhoinao INTEGER,diemtoida DOUBLE,trangthaicauhoi LONG,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table Timekeeping_adminphieudiem";

	public static final String ORDER_BY_JPQL =
		" ORDER BY adminphieudiem.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Timekeeping_adminphieudiem.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public adminphieudiemModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return adminphieudiem.class;
	}

	@Override
	public String getModelClassName() {
		return adminphieudiem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<adminphieudiem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<adminphieudiem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<adminphieudiem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((adminphieudiem)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<adminphieudiem, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<adminphieudiem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(adminphieudiem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<adminphieudiem, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<adminphieudiem, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<adminphieudiem, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<adminphieudiem, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<adminphieudiem, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<adminphieudiem, Object>>();
		Map<String, BiConsumer<adminphieudiem, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<adminphieudiem, ?>>();

		attributeGetterFunctions.put("id", adminphieudiem::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<adminphieudiem, Integer>)adminphieudiem::setId);
		attributeGetterFunctions.put("uuid", adminphieudiem::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<adminphieudiem, String>)adminphieudiem::setUuid);
		attributeGetterFunctions.put("user_id", adminphieudiem::getUser_id);
		attributeSetterBiConsumers.put(
			"user_id",
			(BiConsumer<adminphieudiem, Long>)adminphieudiem::setUser_id);
		attributeGetterFunctions.put(
			"nhomcauhoi", adminphieudiem::getNhomcauhoi);
		attributeSetterBiConsumers.put(
			"nhomcauhoi",
			(BiConsumer<adminphieudiem, String>)adminphieudiem::setNhomcauhoi);
		attributeGetterFunctions.put(
			"noidungcauhoi", adminphieudiem::getNoidungcauhoi);
		attributeSetterBiConsumers.put(
			"noidungcauhoi",
			(BiConsumer<adminphieudiem, String>)
				adminphieudiem::setNoidungcauhoi);
		attributeGetterFunctions.put(
			"thuocnhomcauhoinao", adminphieudiem::getThuocnhomcauhoinao);
		attributeSetterBiConsumers.put(
			"thuocnhomcauhoinao",
			(BiConsumer<adminphieudiem, Integer>)
				adminphieudiem::setThuocnhomcauhoinao);
		attributeGetterFunctions.put("diemtoida", adminphieudiem::getDiemtoida);
		attributeSetterBiConsumers.put(
			"diemtoida",
			(BiConsumer<adminphieudiem, Double>)adminphieudiem::setDiemtoida);
		attributeGetterFunctions.put(
			"trangthaicauhoi", adminphieudiem::getTrangthaicauhoi);
		attributeSetterBiConsumers.put(
			"trangthaicauhoi",
			(BiConsumer<adminphieudiem, Long>)
				adminphieudiem::setTrangthaicauhoi);
		attributeGetterFunctions.put(
			"created_at", adminphieudiem::getCreated_at);
		attributeSetterBiConsumers.put(
			"created_at",
			(BiConsumer<adminphieudiem, Date>)adminphieudiem::setCreated_at);
		attributeGetterFunctions.put(
			"updated_at", adminphieudiem::getUpdated_at);
		attributeSetterBiConsumers.put(
			"updated_at",
			(BiConsumer<adminphieudiem, Date>)adminphieudiem::setUpdated_at);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalId() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("id_"));
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	@JSON
	@Override
	public long getUser_id() {
		return _user_id;
	}

	@Override
	public void setUser_id(long user_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_user_id = user_id;
	}

	@JSON
	@Override
	public String getNhomcauhoi() {
		if (_nhomcauhoi == null) {
			return "";
		}
		else {
			return _nhomcauhoi;
		}
	}

	@Override
	public void setNhomcauhoi(String nhomcauhoi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nhomcauhoi = nhomcauhoi;
	}

	@JSON
	@Override
	public String getNoidungcauhoi() {
		if (_noidungcauhoi == null) {
			return "";
		}
		else {
			return _noidungcauhoi;
		}
	}

	@Override
	public void setNoidungcauhoi(String noidungcauhoi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noidungcauhoi = noidungcauhoi;
	}

	@JSON
	@Override
	public int getThuocnhomcauhoinao() {
		return _thuocnhomcauhoinao;
	}

	@Override
	public void setThuocnhomcauhoinao(int thuocnhomcauhoinao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_thuocnhomcauhoinao = thuocnhomcauhoinao;
	}

	@JSON
	@Override
	public double getDiemtoida() {
		return _diemtoida;
	}

	@Override
	public void setDiemtoida(double diemtoida) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_diemtoida = diemtoida;
	}

	@JSON
	@Override
	public long getTrangthaicauhoi() {
		return _trangthaicauhoi;
	}

	@Override
	public void setTrangthaicauhoi(long trangthaicauhoi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trangthaicauhoi = trangthaicauhoi;
	}

	@JSON
	@Override
	public Date getCreated_at() {
		return _created_at;
	}

	@Override
	public void setCreated_at(Date created_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_created_at = created_at;
	}

	@JSON
	@Override
	public Date getUpdated_at() {
		return _updated_at;
	}

	@Override
	public void setUpdated_at(Date updated_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updated_at = updated_at;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public adminphieudiem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, adminphieudiem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		adminphieudiemImpl adminphieudiemImpl = new adminphieudiemImpl();

		adminphieudiemImpl.setId(getId());
		adminphieudiemImpl.setUuid(getUuid());
		adminphieudiemImpl.setUser_id(getUser_id());
		adminphieudiemImpl.setNhomcauhoi(getNhomcauhoi());
		adminphieudiemImpl.setNoidungcauhoi(getNoidungcauhoi());
		adminphieudiemImpl.setThuocnhomcauhoinao(getThuocnhomcauhoinao());
		adminphieudiemImpl.setDiemtoida(getDiemtoida());
		adminphieudiemImpl.setTrangthaicauhoi(getTrangthaicauhoi());
		adminphieudiemImpl.setCreated_at(getCreated_at());
		adminphieudiemImpl.setUpdated_at(getUpdated_at());

		adminphieudiemImpl.resetOriginalValues();

		return adminphieudiemImpl;
	}

	@Override
	public adminphieudiem cloneWithOriginalValues() {
		adminphieudiemImpl adminphieudiemImpl = new adminphieudiemImpl();

		adminphieudiemImpl.setId(this.<Integer>getColumnOriginalValue("id_"));
		adminphieudiemImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		adminphieudiemImpl.setUser_id(
			this.<Long>getColumnOriginalValue("user_id"));
		adminphieudiemImpl.setNhomcauhoi(
			this.<String>getColumnOriginalValue("nhomcauhoi"));
		adminphieudiemImpl.setNoidungcauhoi(
			this.<String>getColumnOriginalValue("noidungcauhoi"));
		adminphieudiemImpl.setThuocnhomcauhoinao(
			this.<Integer>getColumnOriginalValue("thuocnhomcauhoinao"));
		adminphieudiemImpl.setDiemtoida(
			this.<Double>getColumnOriginalValue("diemtoida"));
		adminphieudiemImpl.setTrangthaicauhoi(
			this.<Long>getColumnOriginalValue("trangthaicauhoi"));
		adminphieudiemImpl.setCreated_at(
			this.<Date>getColumnOriginalValue("created_at"));
		adminphieudiemImpl.setUpdated_at(
			this.<Date>getColumnOriginalValue("updated_at"));

		return adminphieudiemImpl;
	}

	@Override
	public int compareTo(adminphieudiem adminphieudiem) {
		int primaryKey = adminphieudiem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof adminphieudiem)) {
			return false;
		}

		adminphieudiem adminphieudiem = (adminphieudiem)object;

		int primaryKey = adminphieudiem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<adminphieudiem> toCacheModel() {
		adminphieudiemCacheModel adminphieudiemCacheModel =
			new adminphieudiemCacheModel();

		adminphieudiemCacheModel.id = getId();

		adminphieudiemCacheModel.uuid = getUuid();

		String uuid = adminphieudiemCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			adminphieudiemCacheModel.uuid = null;
		}

		adminphieudiemCacheModel.user_id = getUser_id();

		adminphieudiemCacheModel.nhomcauhoi = getNhomcauhoi();

		String nhomcauhoi = adminphieudiemCacheModel.nhomcauhoi;

		if ((nhomcauhoi != null) && (nhomcauhoi.length() == 0)) {
			adminphieudiemCacheModel.nhomcauhoi = null;
		}

		adminphieudiemCacheModel.noidungcauhoi = getNoidungcauhoi();

		String noidungcauhoi = adminphieudiemCacheModel.noidungcauhoi;

		if ((noidungcauhoi != null) && (noidungcauhoi.length() == 0)) {
			adminphieudiemCacheModel.noidungcauhoi = null;
		}

		adminphieudiemCacheModel.thuocnhomcauhoinao = getThuocnhomcauhoinao();

		adminphieudiemCacheModel.diemtoida = getDiemtoida();

		adminphieudiemCacheModel.trangthaicauhoi = getTrangthaicauhoi();

		Date created_at = getCreated_at();

		if (created_at != null) {
			adminphieudiemCacheModel.created_at = created_at.getTime();
		}
		else {
			adminphieudiemCacheModel.created_at = Long.MIN_VALUE;
		}

		Date updated_at = getUpdated_at();

		if (updated_at != null) {
			adminphieudiemCacheModel.updated_at = updated_at.getTime();
		}
		else {
			adminphieudiemCacheModel.updated_at = Long.MIN_VALUE;
		}

		return adminphieudiemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<adminphieudiem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<adminphieudiem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<adminphieudiem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((adminphieudiem)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<adminphieudiem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<adminphieudiem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<adminphieudiem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((adminphieudiem)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, adminphieudiem>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					adminphieudiem.class, ModelWrapper.class);

	}

	private int _id;
	private String _uuid;
	private long _user_id;
	private String _nhomcauhoi;
	private String _noidungcauhoi;
	private int _thuocnhomcauhoinao;
	private double _diemtoida;
	private long _trangthaicauhoi;
	private Date _created_at;
	private Date _updated_at;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<adminphieudiem, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((adminphieudiem)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("user_id", _user_id);
		_columnOriginalValues.put("nhomcauhoi", _nhomcauhoi);
		_columnOriginalValues.put("noidungcauhoi", _noidungcauhoi);
		_columnOriginalValues.put("thuocnhomcauhoinao", _thuocnhomcauhoinao);
		_columnOriginalValues.put("diemtoida", _diemtoida);
		_columnOriginalValues.put("trangthaicauhoi", _trangthaicauhoi);
		_columnOriginalValues.put("created_at", _created_at);
		_columnOriginalValues.put("updated_at", _updated_at);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");
		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("user_id", 4L);

		columnBitmasks.put("nhomcauhoi", 8L);

		columnBitmasks.put("noidungcauhoi", 16L);

		columnBitmasks.put("thuocnhomcauhoinao", 32L);

		columnBitmasks.put("diemtoida", 64L);

		columnBitmasks.put("trangthaicauhoi", 128L);

		columnBitmasks.put("created_at", 256L);

		columnBitmasks.put("updated_at", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private adminphieudiem _escapedModel;

}