/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.backend.model.impl;

import com.liferay.docs.backend.model.Tutiengviet;
import com.liferay.docs.backend.model.TutiengvietModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Tutiengviet service. Represents a row in the &quot;Timekeeping_Tutiengviet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TutiengvietModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TutiengvietImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TutiengvietImpl
 * @generated
 */
@JSON(strict = true)
public class TutiengvietModelImpl
	extends BaseModelImpl<Tutiengviet> implements TutiengvietModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tutiengviet model instance should use the <code>Tutiengviet</code> interface instead.
	 */
	public static final String TABLE_NAME = "Timekeeping_Tutiengviet";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.INTEGER}, {"tieu_de_tv", Types.VARCHAR},
		{"tu_tieng_viet", Types.VARCHAR}, {"created_at", Types.TIMESTAMP},
		{"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tieu_de_tv", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tu_tieng_viet", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Timekeeping_Tutiengviet (id_ INTEGER not null primary key,tieu_de_tv VARCHAR(75) null,tu_tieng_viet VARCHAR(75) null,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table Timekeeping_Tutiengviet";

	public static final String ORDER_BY_JPQL = " ORDER BY tutiengviet.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Timekeeping_Tutiengviet.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TutiengvietModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Tutiengviet.class;
	}

	@Override
	public String getModelClassName() {
		return Tutiengviet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Tutiengviet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Tutiengviet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Tutiengviet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Tutiengviet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Tutiengviet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Tutiengviet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Tutiengviet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Tutiengviet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Tutiengviet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Tutiengviet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Tutiengviet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Tutiengviet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Tutiengviet, Object>>();
		Map<String, BiConsumer<Tutiengviet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Tutiengviet, ?>>();

		attributeGetterFunctions.put("id", Tutiengviet::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Tutiengviet, Integer>)Tutiengviet::setId);
		attributeGetterFunctions.put("tieu_de_tv", Tutiengviet::getTieu_de_tv);
		attributeSetterBiConsumers.put(
			"tieu_de_tv",
			(BiConsumer<Tutiengviet, String>)Tutiengviet::setTieu_de_tv);
		attributeGetterFunctions.put(
			"tu_tieng_viet", Tutiengviet::getTu_tieng_viet);
		attributeSetterBiConsumers.put(
			"tu_tieng_viet",
			(BiConsumer<Tutiengviet, String>)Tutiengviet::setTu_tieng_viet);
		attributeGetterFunctions.put("created_at", Tutiengviet::getCreated_at);
		attributeSetterBiConsumers.put(
			"created_at",
			(BiConsumer<Tutiengviet, Date>)Tutiengviet::setCreated_at);
		attributeGetterFunctions.put("updated_at", Tutiengviet::getUpdated_at);
		attributeSetterBiConsumers.put(
			"updated_at",
			(BiConsumer<Tutiengviet, Date>)Tutiengviet::setUpdated_at);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalId() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("id_"));
	}

	@JSON
	@Override
	public String getTieu_de_tv() {
		if (_tieu_de_tv == null) {
			return "";
		}
		else {
			return _tieu_de_tv;
		}
	}

	@Override
	public void setTieu_de_tv(String tieu_de_tv) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tieu_de_tv = tieu_de_tv;
	}

	@JSON
	@Override
	public String getTu_tieng_viet() {
		if (_tu_tieng_viet == null) {
			return "";
		}
		else {
			return _tu_tieng_viet;
		}
	}

	@Override
	public void setTu_tieng_viet(String tu_tieng_viet) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tu_tieng_viet = tu_tieng_viet;
	}

	@JSON
	@Override
	public Date getCreated_at() {
		return _created_at;
	}

	@Override
	public void setCreated_at(Date created_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_created_at = created_at;
	}

	@JSON
	@Override
	public Date getUpdated_at() {
		return _updated_at;
	}

	@Override
	public void setUpdated_at(Date updated_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updated_at = updated_at;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Tutiengviet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Tutiengviet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TutiengvietImpl tutiengvietImpl = new TutiengvietImpl();

		tutiengvietImpl.setId(getId());
		tutiengvietImpl.setTieu_de_tv(getTieu_de_tv());
		tutiengvietImpl.setTu_tieng_viet(getTu_tieng_viet());
		tutiengvietImpl.setCreated_at(getCreated_at());
		tutiengvietImpl.setUpdated_at(getUpdated_at());

		tutiengvietImpl.resetOriginalValues();

		return tutiengvietImpl;
	}

	@Override
	public Tutiengviet cloneWithOriginalValues() {
		TutiengvietImpl tutiengvietImpl = new TutiengvietImpl();

		tutiengvietImpl.setId(this.<Integer>getColumnOriginalValue("id_"));
		tutiengvietImpl.setTieu_de_tv(
			this.<String>getColumnOriginalValue("tieu_de_tv"));
		tutiengvietImpl.setTu_tieng_viet(
			this.<String>getColumnOriginalValue("tu_tieng_viet"));
		tutiengvietImpl.setCreated_at(
			this.<Date>getColumnOriginalValue("created_at"));
		tutiengvietImpl.setUpdated_at(
			this.<Date>getColumnOriginalValue("updated_at"));

		return tutiengvietImpl;
	}

	@Override
	public int compareTo(Tutiengviet tutiengviet) {
		int primaryKey = tutiengviet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Tutiengviet)) {
			return false;
		}

		Tutiengviet tutiengviet = (Tutiengviet)object;

		int primaryKey = tutiengviet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Tutiengviet> toCacheModel() {
		TutiengvietCacheModel tutiengvietCacheModel =
			new TutiengvietCacheModel();

		tutiengvietCacheModel.id = getId();

		tutiengvietCacheModel.tieu_de_tv = getTieu_de_tv();

		String tieu_de_tv = tutiengvietCacheModel.tieu_de_tv;

		if ((tieu_de_tv != null) && (tieu_de_tv.length() == 0)) {
			tutiengvietCacheModel.tieu_de_tv = null;
		}

		tutiengvietCacheModel.tu_tieng_viet = getTu_tieng_viet();

		String tu_tieng_viet = tutiengvietCacheModel.tu_tieng_viet;

		if ((tu_tieng_viet != null) && (tu_tieng_viet.length() == 0)) {
			tutiengvietCacheModel.tu_tieng_viet = null;
		}

		Date created_at = getCreated_at();

		if (created_at != null) {
			tutiengvietCacheModel.created_at = created_at.getTime();
		}
		else {
			tutiengvietCacheModel.created_at = Long.MIN_VALUE;
		}

		Date updated_at = getUpdated_at();

		if (updated_at != null) {
			tutiengvietCacheModel.updated_at = updated_at.getTime();
		}
		else {
			tutiengvietCacheModel.updated_at = Long.MIN_VALUE;
		}

		return tutiengvietCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Tutiengviet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Tutiengviet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Tutiengviet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Tutiengviet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Tutiengviet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Tutiengviet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Tutiengviet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Tutiengviet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Tutiengviet>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Tutiengviet.class, ModelWrapper.class);

	}

	private int _id;
	private String _tieu_de_tv;
	private String _tu_tieng_viet;
	private Date _created_at;
	private Date _updated_at;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Tutiengviet, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Tutiengviet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("tieu_de_tv", _tieu_de_tv);
		_columnOriginalValues.put("tu_tieng_viet", _tu_tieng_viet);
		_columnOriginalValues.put("created_at", _created_at);
		_columnOriginalValues.put("updated_at", _updated_at);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("tieu_de_tv", 2L);

		columnBitmasks.put("tu_tieng_viet", 4L);

		columnBitmasks.put("created_at", 8L);

		columnBitmasks.put("updated_at", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Tutiengviet _escapedModel;

}